nname: test
channels:
  - conda-forge
#  - defaults
dependencies:
  - check-manifest 
  - netifaces
  - psutil
  - pytest
  - pytest-cov
  - python=3.8
  - setuptools
  - twine
  - zeroconf
  - myst-parser
  - sphinx
#   - sphinx_book_theme # not available on conda-forge
