name: Run tests
on:
  push:
    branches:
      - master
    paths:
      - 'spyder-remote-server/**'
      - 'spyder-remote-client/**'
  pull_request:
    branches:
      - master
    paths:
      - 'spyder-remote-server/**'
      - 'spyder-remote-client/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install lint dependencies
        run: |
          pip install pre-commit check-manifest
# take black out
#       - name: Check pre commits
#         run: |
#           pre-commit run -a
      - name: Check manifest Server
        run: |
          cd spyder-remote-server
          check-manifest
      - name: Check manifest Client
        run: |
          cd spyder-remote-client
          check-manifest

  test-client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Client dependencies
        run: |
          cd spyder-remote-client
          pip install -r requirements/run.txt
          pip install -r requirements/test.txt
      - name: Client Tests
        run: |
          cd spyder-remote-client
          pytest tests/ --cov=spyder_remote_client

  test-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Server dependencies
        run: |
          cd spyder-remote-server
          pip install -r requirements/run.txt
          pip install -r requirements/test.txt
      - name: Server Tests
        run: |
          cd spyder-remote-server
          pytest tests/ --cov=spyder_remote_server
